name: geotag
description: A Flutter desktop photos geotagging client
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0-71.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chicago: any
  clock: any
  collection: any
  file: any
  file_picker: any
  image: any
  intl: any
  material_symbols_icons: ^4.2718.0
  path_provider: any
  platform_native:
    path: packages/platform_native
  sqflite: any
  sqflite_common_ffi: any
  video_player: any
  webview_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  meta: any
  plugin_platform_interface: any
  webview_flutter_platform_interface: any

dependency_overrides:
  webview_flutter_wkwebview:
    git:
      url: https://github.com/stuartmorgan/packages
      path: packages/webview_flutter/webview_flutter_wkwebview
      ref: webview-macos

flutter:
  uses-material-design: true
  assets:
    - assets/
  