name: geotag
description: A Flutter desktop photos geotagging client
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0-71.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chicago: any
  clock: any
  collection: any
  file: any
  file_picker: ^5.2.4
  image: any
  intl: any
  path_provider: any
  platform_native:
    path: packages/platform_native
  sqflite: any
  sqflite_common_ffi: any
  video_player: ^2.8.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  meta: ^1.11.0
  plugin_platform_interface: ^2.1.8
  webview_flutter_platform_interface: ^2.10.0

dependency_overrides:
  webview_flutter_wkwebview:
    git:
      url: https://github.com/stuartmorgan/packages
      path: packages/webview_flutter/webview_flutter_wkwebview
      ref: webview-macos

flutter:
  uses-material-design: true
  assets:
    - assets/
  